//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaCrawler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MangaCrawler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters: {0}.
        /// </summary>
        internal static string CHAPTERS {
            get {
                return ResourceManager.GetString("CHAPTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETING.
        /// </summary>
        internal static string DELETING {
            get {
                return ResourceManager.GetString("DELETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory path is invalid: &apos;{0}&apos;.
        /// </summary>
        internal static string DIR_ERROR_1 {
            get {
                return ResourceManager.GetString("DIR_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create directory: &apos;{0}&apos;.
        /// </summary>
        internal static string DIR_ERROR_2 {
            get {
                return ResourceManager.GetString("DIR_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DOWNLOADED {
            get {
                return ResourceManager.GetString("DOWNLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading in progress. Exit anyway?.
        /// </summary>
        internal static string EXIT_QUESTION {
            get {
                return ResourceManager.GetString("EXIT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://mangacrawler.codeplex.com/.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series: {0}.
        /// </summary>
        internal static string SERIES {
            get {
                return ResourceManager.GetString("SERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAITING.
        /// </summary>
        internal static string WAITING {
            get {
                return ResourceManager.GetString("WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIPPING.
        /// </summary>
        internal static string ZIPPING {
            get {
                return ResourceManager.GetString("ZIPPING", resourceCulture);
            }
        }
    }
}
